"""Explicit scraper source-contract states for dashboard Health labels."""
from __future__ import annotations

SCRAPER_SOURCE_STATES: dict[str, str] = {
    # Listing-only parsers with verified public contracts and bounded source smoke.
    "Putnam (TN)": "verified_public",
    "Randall (TX)": "verified_public",
    "Bossier (LA)": "verified_public",
    "Tangipahoa (LA)": "verified_public",
    "St. Mary (LA)": "verified_public",
    "Lee (AL)": "verified_public",
    "Marshall (AL)": "verified_public",
    "Etowah (AL)": "verified_public",
    "St. Clair (AL)": "verified_public",
    "Rankin (MS)": "verified_public",
    # Deployed guards: no source fetches and no record emission pending revalidation.
    "Calcasieu (LA)": "fail_closed",
    "East Baton Rouge (LA)": "fail_closed",
    "Jefferson (LA)": "fail_closed",
    "Ascension (LA)": "fail_closed",
    "Caddo (LA)": "fail_closed",
    "Lafayette (LA)": "fail_closed",
    "Livingston (LA)": "fail_closed",
    "Ouachita (LA)": "fail_closed",
    "Forsyth (NC)": "fail_closed",
    "Madison (AL)": "fail_closed",
    "Mobile (AL)": "fail_closed",
    "Statewide (CT)": "fail_closed",
    "Bridgeport (CT)": "fail_closed",
    "Hartford (CT)": "fail_closed",
    "New Haven (CT)": "fail_closed",
    "Stamford (CT)": "fail_closed",
    "Anderson (SC)": "fail_closed",
    "Bamberg (SC)": "fail_closed",
    "Beaufort (SC)": "fail_closed",
    "Berkeley (SC)": "fail_closed",
    "Greenville (SC)": "fail_closed",
    "Horry (SC)": "fail_closed",
    "Jasper (SC)": "fail_closed",
    "Kershaw (SC)": "fail_closed",
    "Laurens (SC)": "fail_closed",
    "Lee (SC)": "fail_closed",
    "Marion (SC)": "fail_closed",
    "Saluda (SC)": "fail_closed",
    "Union (SC)": "fail_closed",
    "York (SC)": "fail_closed",
    "Caldwell (NC)": "fail_closed",
    "Chatham (NC)": "fail_closed",
    "Cumberland (NC)": "fail_closed",
    "Davidson (NC)": "fail_closed",
    "Guilford (NC)": "fail_closed",
    "Halifax (NC)": "fail_closed",
    "Randolph (NC)": "fail_closed",
    "Scotland (NC)": "fail_closed",
    "Union (NC)": "fail_closed",
    "Wake (NC)": "fail_closed",
    "Davidson (TN)": "fail_closed",
    "Hamilton (TN)": "fail_closed",
    "Knox (TN)": "fail_closed",
    "Montgomery (TN)": "fail_closed",
    "Rutherford (TN)": "fail_closed",
    "Shelby (TN)": "fail_closed",
    "Sumner (TN)": "fail_closed",
    "Williamson (TN)": "fail_closed",
    "Wilson (TN)": "fail_closed",
    "Orleans (LA)": "fail_closed",
    "St. Tammany (LA)": "fail_closed",
    "Blount (TN)": "fail_closed",
    "Bradley (TN)": "fail_closed",
    "Sevier (TN)": "fail_closed",
    "Washington (TN)": "fail_closed",
    "Maury (TN)": "fail_closed",
    "Robertson (TN)": "fail_closed",
    "Hamblen (TN)": "fail_closed",
    "Bedford (TN)": "fail_closed",
    "Coffee (TN)": "fail_closed",
    "Lincoln (TN)": "fail_closed",
    "Giles (TN)": "fail_closed",
    "Baldwin (AL)": "fail_closed",
    "Cullman (AL)": "fail_closed",
    "DeKalb (AL)": "fail_closed",
    "Houston (AL)": "fail_closed",
    "Jackson (AL)": "fail_closed",
    "Jefferson (AL)": "fail_closed",
    "Morgan (AL)": "fail_closed",
    "Shelby (AL)": "fail_closed",
    "Tuscaloosa (AL)": "fail_closed",
    "DeSoto (MS)": "fail_closed",
    "Forrest (MS)": "fail_closed",
    "Harrison (MS)": "fail_closed",
    "Hinds (MS)": "fail_closed",
    "Jackson (MS)": "fail_closed",
    "Jones (MS)": "fail_closed",
    "Lauderdale (MS)": "fail_closed",
    "Madison (MS)": "fail_closed",
    "Sarasota (FL)": "fail_closed",
    # Runtime-gated FL scopes aligned to Health Source Guards (SCRAPER_SOURCE_STATES).
    # Broward: always-empty / missing from registry caused unverified + Run offer.
    # Baker/Calhoun/Gulf/Holmes/Levy/Wakulla/Washington: FL JailTracker runtime-gated.
    "Broward (FL)": "fail_closed",
    "Baker (FL)": "fail_closed",
    "Calhoun (FL)": "fail_closed",
    "Gulf (FL)": "fail_closed",
    "Holmes (FL)": "fail_closed",
    "Levy (FL)": "fail_closed",
    "Wakulla (FL)": "fail_closed",
    "Washington (FL)": "fail_closed",
    # Ohio pilot scopes are registered for truthful health visibility only.
    # They remain blocked before source fetch until county-specific approval.
    "Clermont (OH)": "fail_closed",
    "Clinton (OH)": "fail_closed",
    "Huron (OH)": "fail_closed",
}
