"""
PoisonPillDetector — WAF / Anti-Bot / CAPTCHA Response Detection

Inspects HTTP responses and HTML content for signs that the request
was intercepted by a WAF, anti-bot system, or CAPTCHA challenge.

Used by BaseScraper to classify scraper failures and determine
whether to retry (transient block) or disable (persistent block).

Supports detection of:
- Cloudflare (cf-mitigated, ray-id, challenge page)
- AWS WAF / Shield
- Imperva / Incapsula
- reCAPTCHA / hCaptcha / Turnstile
- Generic 403/429/503 block pages
- County-specific jail roster patterns
"""

import re
import logging
from dataclasses import dataclass
from typing import Optional

logger = logging.getLogger(__name__)


@dataclass
class PoisonPillResult:
    """Result of a poison pill check."""
    is_poisoned: bool
    detection_type: str  # 'clean', 'waf', 'captcha', 'rate_limit', 'block_page', 'empty'
    vendor: str  # 'cloudflare', 'aws_waf', 'imperva', 'recaptcha', 'generic', ''
    confidence: float  # 0.0 - 1.0
    detail: str  # Human-readable description
    should_retry: bool  # True = transient, False = persistent block


class PoisonPillDetector:
    """
    Detect WAF/CAPTCHA/anti-bot responses that contain no real arrest data.

    Usage:
        detector = PoisonPillDetector()
        result = detector.check_response(response)
        if result.is_poisoned:
            if result.should_retry:
                # wait and retry
            else:
                # disable scraper, escalate
    """

    # ── Cloudflare Signatures ──
    _CF_HEADERS = {"cf-ray", "cf-mitigated", "cf-cache-status"}
    _CF_CHALLENGE_PATTERNS = [
        r"Checking your browser",
        r"Please turn JavaScript on",
        r"cf-browser-verification",
        r"cloudflare\.com/cdn-cgi",
        r"Attention Required! \| Cloudflare",
        r"__cf_chl_managed_tk__",
        r"challenge-platform",
    ]

    # ── AWS WAF / Shield ──
    _AWS_WAF_PATTERNS = [
        r"Request blocked",
        r"aws-waf-token",
        r"<title>ERROR: The request could not be satisfied</title>",
        r"Generated by cloudfront",
    ]

    # ── Imperva / Incapsula ──
    _IMPERVA_PATTERNS = [
        r"incapsula\.com",
        r"_Incapsula_Resource",
        r"visid_incap_",
        r"Request unsuccessful\. Incapsula",
    ]

    # ── CAPTCHA Systems ──
    _CAPTCHA_PATTERNS = [
        r"g-recaptcha",
        r"recaptcha/api",
        r"www\.google\.com/recaptcha",
        r"hcaptcha\.com",
        r"h-captcha",
        r"challenges\.cloudflare\.com/turnstile",
        r"cf-turnstile",
    ]

    # ── Generic Block Page Indicators ──
    _BLOCK_PATTERNS = [
        r"Access Denied",
        r"Access to this page has been denied",
        r"Your access to this site has been limited",
        r"Error 1015",  # Cloudflare rate limit
        r"Error 1020",  # Cloudflare access denied
        r"You have been blocked",
        r"This website is using a security service",
        r"Pardon Our Interruption",  # Distil Networks
        r"Please verify you are a human",
        r"Bot detection",
        r"Automated access detected",
    ]

    # ── Minimum valid content thresholds ──
    # A real jail roster page should have substantial HTML content
    _MIN_CONTENT_LENGTH = 500  # bytes
    _MIN_HTML_TAGS = 5  # minimum number of HTML tags expected

    def check_response(
        self,
        status_code: int = 200,
        headers: Optional[dict] = None,
        body: str = "",
        url: str = "",
    ) -> PoisonPillResult:
        """
        Analyze an HTTP response for WAF/anti-bot/CAPTCHA indicators.

        Args:
            status_code: HTTP status code
            headers: Response headers (dict)
            body: Response body text/HTML
            url: Request URL (for logging)

        Returns:
            PoisonPillResult with detection details
        """
        headers = headers or {}
        header_lower = {k.lower(): v for k, v in headers.items()}

        # ── Check 1: HTTP status codes ──
        if status_code == 403:
            detail = self._match_body_patterns(body)
            vendor = self._identify_vendor(header_lower, body)
            return PoisonPillResult(
                is_poisoned=True,
                detection_type="waf",
                vendor=vendor,
                confidence=0.95,
                detail=detail or f"403 Forbidden — likely WAF block ({vendor})",
                should_retry=False,  # 403 is usually persistent
            )

        if status_code == 429:
            retry_after = header_lower.get("retry-after", "")
            return PoisonPillResult(
                is_poisoned=True,
                detection_type="rate_limit",
                vendor=self._identify_vendor(header_lower, body),
                confidence=0.99,
                detail=f"429 Rate Limited (retry-after: {retry_after})",
                should_retry=True,  # Rate limits are transient
            )

        if status_code == 503:
            vendor = self._identify_vendor(header_lower, body)
            is_challenge = any(
                re.search(p, body, re.IGNORECASE)
                for p in self._CF_CHALLENGE_PATTERNS
            )
            return PoisonPillResult(
                is_poisoned=True,
                detection_type="waf" if is_challenge else "block_page",
                vendor=vendor,
                confidence=0.85,
                detail=f"503 Service Unavailable — {'challenge page' if is_challenge else 'block page'} ({vendor})",
                should_retry=is_challenge,  # Challenges are sometimes transient
            )

        if status_code >= 400:
            return PoisonPillResult(
                is_poisoned=True,
                detection_type="block_page",
                vendor="generic",
                confidence=0.7,
                detail=f"HTTP {status_code} error response",
                should_retry=status_code >= 500,
            )

        # ── Check 2: Empty or suspiciously small body ──
        if len(body.strip()) < self._MIN_CONTENT_LENGTH:
            return PoisonPillResult(
                is_poisoned=True,
                detection_type="empty",
                vendor="",
                confidence=0.6,
                detail=f"Response body too small ({len(body.strip())} bytes, minimum {self._MIN_CONTENT_LENGTH})",
                should_retry=True,
            )

        # ── Check 3: CAPTCHA detection ──
        for pattern in self._CAPTCHA_PATTERNS:
            if re.search(pattern, body, re.IGNORECASE):
                vendor = self._identify_vendor(header_lower, body)
                return PoisonPillResult(
                    is_poisoned=True,
                    detection_type="captcha",
                    vendor=vendor,
                    confidence=0.95,
                    detail=f"CAPTCHA detected: {pattern} ({vendor})",
                    should_retry=False,  # CAPTCHAs need proxy rotation
                )

        # ── Check 4: Cloudflare challenge page (200 status but challenge body) ──
        for pattern in self._CF_CHALLENGE_PATTERNS:
            if re.search(pattern, body, re.IGNORECASE):
                return PoisonPillResult(
                    is_poisoned=True,
                    detection_type="waf",
                    vendor="cloudflare",
                    confidence=0.9,
                    detail=f"Cloudflare challenge page detected: {pattern}",
                    should_retry=True,
                )

        # ── Check 5: Generic block pages ──
        for pattern in self._BLOCK_PATTERNS:
            if re.search(pattern, body, re.IGNORECASE):
                vendor = self._identify_vendor(header_lower, body)
                return PoisonPillResult(
                    is_poisoned=True,
                    detection_type="block_page",
                    vendor=vendor,
                    confidence=0.8,
                    detail=f"Block page detected: {pattern}",
                    should_retry=False,
                )

        # ── Check 6: Imperva/Incapsula ──
        for pattern in self._IMPERVA_PATTERNS:
            if re.search(pattern, body, re.IGNORECASE):
                return PoisonPillResult(
                    is_poisoned=True,
                    detection_type="waf",
                    vendor="imperva",
                    confidence=0.9,
                    detail=f"Imperva/Incapsula WAF detected: {pattern}",
                    should_retry=False,
                )

        # ── Check 7: AWS WAF ──
        for pattern in self._AWS_WAF_PATTERNS:
            if re.search(pattern, body, re.IGNORECASE):
                return PoisonPillResult(
                    is_poisoned=True,
                    detection_type="waf",
                    vendor="aws_waf",
                    confidence=0.85,
                    detail=f"AWS WAF/CloudFront detected: {pattern}",
                    should_retry=False,
                )

        # ── All clear ──
        return PoisonPillResult(
            is_poisoned=False,
            detection_type="clean",
            vendor="",
            confidence=1.0,
            detail="Response appears clean",
            should_retry=False,
        )

    def _identify_vendor(self, headers: dict, body: str) -> str:
        """Identify the WAF/CDN vendor from headers and body."""
        # Cloudflare
        if any(h in headers for h in self._CF_HEADERS):
            return "cloudflare"
        if "server" in headers and "cloudflare" in headers["server"].lower():
            return "cloudflare"

        # AWS
        if "x-amzn-requestid" in headers or "x-amz-cf-id" in headers:
            return "aws_waf"
        if "server" in headers and "amazons3" in headers["server"].lower():
            return "aws_waf"

        # Imperva
        if "x-iinfo" in headers:
            return "imperva"
        if any(re.search(p, body, re.IGNORECASE) for p in self._IMPERVA_PATTERNS):
            return "imperva"

        # Sucuri
        if "x-sucuri-id" in headers:
            return "sucuri"

        # Akamai
        if "x-akamai-transformed" in headers:
            return "akamai"

        return "generic"

    def _match_body_patterns(self, body: str) -> Optional[str]:
        """Find the first matching block pattern in body."""
        all_patterns = (
            self._CF_CHALLENGE_PATTERNS
            + self._CAPTCHA_PATTERNS
            + self._BLOCK_PATTERNS
            + self._IMPERVA_PATTERNS
            + self._AWS_WAF_PATTERNS
        )
        for pattern in all_patterns:
            match = re.search(pattern, body, re.IGNORECASE)
            if match:
                return f"Matched: {pattern} → '{match.group()[:80]}'"
        return None

    def check_html(self, html: str, url: str = "") -> PoisonPillResult:
        """
        Convenience method: check raw HTML content (assumes 200 OK status).
        Use when you have HTML from a browser-based scraper (DrissionPage, Selenium)
        where you don't have direct access to HTTP status codes.
        """
        return self.check_response(
            status_code=200,
            headers={},
            body=html,
            url=url,
        )
