#!/usr/bin/env bash
# ShamrockLeads — Codex Cloud manual setup
# ========================================
# Paste this file's contents into Codex → Environment → Code execution →
# Setup script = Manual.  Automatic setup is the wrong choice here:
# `pip install -r requirements.txt` pulls Playwright, nodriver, Selenium,
# pdfservices-sdk, and scraper extras that blow time/disk and are unused
# for unit tests.
#
# Codex rules this script relies on:
#   - Setup has internet. The agent phase does not (unless you enable it).
#   - `export` in this script does NOT persist. Write ~/.bashrc + .env.
#   - Secrets exist only during setup. Copy them into .env here if the
#     agent/tests need them. Never echo secret values.
set -euo pipefail

ROOT="${CODEX_WORKDIR:-$(pwd)}"
if [ -d /workspace/shamrock-leads ]; then
  ROOT=/workspace/shamrock-leads
fi
cd "$ROOT"

echo "==> Shamrock Codex setup in $ROOT"

export DEBIAN_FRONTEND=noninteractive
if command -v apt-get >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo apt-get install -y -qq --no-install-recommends \
    python3 python3-venv python3-pip python3-dev \
    tesseract-ocr libtesseract-dev \
    git curl ca-certificates \
    >/dev/null
fi

VENV_DIR="/opt/shamrock-venv"
if ! python3 -m venv "$VENV_DIR" 2>/dev/null; then
  VENV_DIR="${HOME}/shamrock-venv"
  python3 -m venv "$VENV_DIR"
fi
# shellcheck disable=SC1091
source "${VENV_DIR}/bin/activate"
python -m pip install --upgrade pip wheel setuptools >/dev/null

# Lean test/dev stack — not the full scraper image.
# motor is required: dashboard.extensions imports AsyncIOMotorClient at import time.
python -m pip install --no-cache-dir \
  "fastapi>=0.115.0,<0.120.0" \
  "starlette>=0.37.0,<0.41.0" \
  "uvicorn[standard]>=0.30.0" \
  "httpx>=0.27.0" \
  "aiohttp>=3.9.0" \
  "pytest>=8.0.0" \
  "pytest-asyncio>=0.23.0" \
  "python-multipart>=0.0.9" \
  "itsdangerous>=2.1.2" \
  "Pillow>=10.0.0" \
  "pymongo>=4.6.0" \
  "motor>=3.3.0" \
  "python-dotenv>=1.0.0" \
  "pydantic>=2.0.0" \
  "beautifulsoup4>=4.12.0" \
  "requests>=2.31.0" \
  "PyYAML>=6.0" \
  "python-dateutil>=2.8.0"

# Persist PATH / PYTHONPATH for the agent bash session.
{
  echo ""
  echo "# Shamrock Codex Cloud"
  echo "source ${VENV_DIR}/bin/activate"
  echo "export PYTHONPATH=\"${ROOT}:\${PYTHONPATH:-}\""
  echo "export PYTHONDONTWRITEBYTECODE=1"
  echo "export PYTHONUNBUFFERED=1"
  echo "export MONGODB_DB_NAME=\"\${MONGODB_DB_NAME:-ShamrockBailDB}\""
  echo "export DASHBOARD_PUBLIC_URL=\"\${DASHBOARD_PUBLIC_URL:-https://leads.shamrockbailbonds.biz}\""
  echo "export DOCUSEAL_URL=\"\${DOCUSEAL_URL:-https://sign.shamrockbailbonds.biz}\""
  echo "export TRAPE_SERVER_URL=\"\${TRAPE_SERVER_URL:-https://leads.shamrockbailbonds.biz}\""
  echo "export OSINT_WORKER_URL=\"\${OSINT_WORKER_URL:-http://osint-worker:5065}\""
  echo "cd \"${ROOT}\" 2>/dev/null || true"
} >> "${HOME}/.bashrc"

# Build a local .env from env vars + setup-only secrets (gitignored).
# Secrets are stripped after setup; writing them here is how tests see them.
ENV_FILE="${ROOT}/.env"
if [ ! -f "$ENV_FILE" ]; then
  umask 077
  {
    echo "# Generated by scripts/codex_cloud_setup.sh — do not commit"
    echo "MONGODB_DB_NAME=${MONGODB_DB_NAME:-ShamrockBailDB}"
    echo "DASHBOARD_PUBLIC_URL=${DASHBOARD_PUBLIC_URL:-https://leads.shamrockbailbonds.biz}"
    echo "DOCUSEAL_URL=${DOCUSEAL_URL:-https://sign.shamrockbailbonds.biz}"
    echo "TRAPE_SERVER_URL=${TRAPE_SERVER_URL:-https://leads.shamrockbailbonds.biz}"
    echo "OSINT_WORKER_URL=${OSINT_WORKER_URL:-http://osint-worker:5065}"
    echo "OSINT_ALLOW_INSECURE=${OSINT_ALLOW_INSECURE:-true}"
    echo "DASHBOARD_PIN=${DASHBOARD_PIN:-codex-dev-pin}"
    echo "SECRET_KEY=${SECRET_KEY:-codex-dev-secret-not-for-prod}"
    # Optional secrets — only written if present in the setup environment
    [ -n "${MONGODB_URI:-}" ] && echo "MONGODB_URI=${MONGODB_URI}"
    [ -n "${OPENAI_API_KEY:-}" ] && echo "OPENAI_API_KEY=${OPENAI_API_KEY}"
    [ -n "${DOCUSEAL_API_KEY:-}" ] && echo "DOCUSEAL_API_KEY=${DOCUSEAL_API_KEY}"
    [ -n "${HUNTER_API_KEY:-}" ] && echo "HUNTER_API_KEY=${HUNTER_API_KEY}"
    [ -n "${OSINT_WORKER_KEY:-}" ] && echo "OSINT_WORKER_KEY=${OSINT_WORKER_KEY}"
    [ -n "${GAS_API_KEY:-}" ] && echo "GAS_API_KEY=${GAS_API_KEY}"
    true
  } > "$ENV_FILE"
  echo "==> wrote ${ENV_FILE} (secrets omitted if unset)"
else
  echo "==> ${ENV_FILE} already exists — leaving in place"
fi

# Smoke: parser/unit tests that need no live Mongo or network.
# Non-fatal: a collection/import miss must not block the Codex environment.
export PYTHONPATH="${ROOT}:${PYTHONPATH:-}"
if python -m pytest tests/test_id_scanner_service.py tests/test_id_ocr_service.py tests/test_osint_worker_hookup.py tests/test_palantir_intel.py -q --tb=line; then
  echo "==> Codex setup OK (smoke tests passed)"
else
  echo "==> Codex setup OK (smoke tests skipped/failed — env is still usable)"
fi
